# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sqlconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('sqltext', models.CharField(max_length=20000)),
                ('treater', models.CharField(max_length=128)),
                ('condtion', models.CharField(choices=[('1', '\u5df2\u6267\u884c'), ('2', '\u5f85\u6267\u884c'), ('3', '\u5df2\u62d2\u7edd'), ('4', '\u5df2\u56de\u6eda')], max_length=1)),
                ('env', models.CharField(blank=True, choices=[('1', '\u751f\u4ea7'), ('2', '\u6d4b\u8bd5')], max_length=1, null=True)),
                ('operate', models.CharField(blank=True, choices=[('1', '\u6267\u884c'), ('2', '\u62d2\u7edd'), ('3', '\u56de\u6eda')], max_length=1, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
