# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0003_auto_20180307_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconf',
            name='sqltext',
            field=models.CharField(max_length=20000),
        ),
    ]
