# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0007_auto_20180307_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlconf',
            old_name='sqltext',
            new_name='sqlcontent',
        ),
    ]
