# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0008_auto_20180307_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlconf',
            old_name='user',
            new_name='sqlname',
        ),
    ]
