# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0009_auto_20180307_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlconf',
            name='password',
        ),
    ]
