# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0010_remove_sqlconf_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlconf',
            name='backdb',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sqlconf',
            name='backid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sqlconf',
            name='condtion',
            field=models.CharField(choices=[('1', '\u5f85\u6267\u884c'), ('2', '\u5df2\u6267\u884c'), ('3', '\u5df2\u62d2\u7edd'), ('4', '\u5df2\u56de\u6eda')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='sqlconf',
            name='operate',
            field=models.CharField(blank=True, choices=[('1', '\u6267\u884c'), ('2', '\u62d2\u7edd'), ('3', '\u56de\u6eda')], default=1, max_length=1, null=True),
        ),
    ]
