# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0011_auto_20180308_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlconf',
            old_name='sqlname',
            new_name='username',
        ),
    ]
