# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4e66\u540d')),
                ('publication_date', models.DateField(verbose_name='\u51fa\u7248\u65f6\u95f4')),
                ('authors', models.ManyToManyField(to='books.Author', verbose_name='\u4f5c\u8005')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publish', verbose_name='\u51fa\u7248\u793e')),
            ],
            options={
                'ordering': ['-publication_date'],
                'verbose_name': '\u56fe\u4e66\u4fe1\u606f',
                'verbose_name_plural': '\u56fe\u4e66\u4fe1\u606f',
            },
        ),
    ]
