# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180114_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish',
            old_name='publish',
            new_name='city',
        ),
    ]
