# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='instance_name',
            field=models.CharField(max_length=256, verbose_name='\u5b9e\u4f8b\u7684\u663e\u793a\u540d\u79f0'),
        ),
    ]
