# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0002_auto_20180314_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbconf',
            old_name='userobj',
            new_name='user',
        ),
    ]
