# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0004_auto_20180315_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlconf',
            name='backdb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
