# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0005_auto_20180316_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlconf',
            name='operate',
        ),
        migrations.AddField(
            model_name='sqlconf',
            name='daiwork',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
