# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180108_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
                ('createtime', models.DateField(auto_now_add=True, null=True)),
                ('updatetime', models.DateField(auto_now=True, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('fans', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
                ('createtime', models.DateField(auto_now_add=True, null=True)),
                ('updatetime', models.DateField(auto_now=True, null=True)),
                ('city', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='app1.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Publish'),
        ),
    ]
