# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-05 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20171231_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lastselect',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='readnum',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=b'', max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[(b'0', '\u65e0'), (b'1', '\u603b\u76d1'), (b'2', '\u7ecf\u7406'), (b'3', '\u7814\u53d1')], default=b'0', max_length=1),
        ),
    ]
