# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-18 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('leaderid', models.IntegerField(blank=True, null=True)),
                ('readnum', models.IntegerField(blank=True, null=True)),
                ('lastselect', models.CharField(blank=True, default=b'', max_length=128)),
                ('role', models.CharField(blank=True, choices=[('0', '\u65e0'), ('1', '\u603b\u76d1'), ('2', '\u7ecf\u7406'), ('3', '\u7814\u53d1')], default='0', max_length=32, null=True)),
                ('note', models.CharField(blank=True, default=b'', max_length=128)),
            ],
        ),
    ]
