# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='leaderid',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='readnum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
