# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171024_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='readnum',
            field=models.CharField(blank=True, default='0', max_length=2, null=True),
        ),
    ]
