# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('fansnum', models.IntegerField(default=0, verbose_name='\u7c89\u4e1d\u91cf')),
                ('income', models.IntegerField(default=0, verbose_name='\u6536\u5165')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('price', models.IntegerField()),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('clicknum', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf')),
                ('sellnum', models.IntegerField(default=0, verbose_name='\u9500\u91cf')),
                ('author', models.ManyToManyField(blank=True, null=True, to='app1.Author')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('city', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Publish'),
        ),
    ]
