# Generated by Django 2.0 on 2018-04-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEchartsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True, verbose_name='处理结果')),
            ],
            options={
                'verbose_name': 'work_echarts_data',
                'verbose_name_plural': 'work_echarts_data',
                'ordering': ['-pk'],
            },
        ),
    ]
