# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180114_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='price',
        ),
    ]
