# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0002_deploy_detail_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='detail_result',
            field=models.TextField(verbose_name='\u6267\u884c\u7ed3\u679c\u8be6\u60c5'),
        ),
    ]
