# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0003_auto_20180509_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='detail_result',
        ),
        migrations.AddField(
            model_name='deploy',
            name='formal_result',
            field=models.TextField(default='', verbose_name='\u6b63\u5f0f\u73af\u5883\u6267\u884c\u7ed3\u679c\u8be6\u60c5'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='test_result',
            field=models.TextField(default='', verbose_name='\u6d4b\u8bd5\u73af\u5883\u6267\u884c\u7ed3\u679c\u8be6\u60c5'),
        ),
    ]
