# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0004_auto_20180509_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploy',
            old_name='test_result',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='formal_result',
        ),
    ]
