# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0005_auto_20180509_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='env',
            field=models.IntegerField(choices=[(0, '\u6d4b\u8bd5'), (1, '\u6b63\u5f0f')], default=0, verbose_name='\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(0, '\u7533\u8bf7'), (1, '\u6d4b\u8bd5'), (2, '\u4e0a\u7ebf'), (3, '\u53d6\u6d88\u4e0a\u7ebf')], default=0, verbose_name='\u4e0a\u7ebf\u72b6\u6001'),
        ),
    ]
