# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0006_auto_20180510_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='env',
        ),
    ]
