# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0007_remove_deploy_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='version_desc',
            field=models.CharField(default='', max_length=100, verbose_name='\u7248\u672c\u63cf\u8ff0'),
        ),
    ]
