# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0008_auto_20180510_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='version_desc',
            field=models.CharField(max_length=100, null=True, verbose_name='\u7248\u672c\u63cf\u8ff0'),
        ),
    ]
