# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_release', '0009_auto_20180510_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='env',
            field=models.IntegerField(choices=[(0, '\u6d4b\u8bd5\u73af\u5883'), (1, '\u5f00\u53d1\u73af\u5883')], default=0, verbose_name='\u53d1\u5e03\u73af\u5883'),
        ),
    ]
