# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='type0',
            field=models.IntegerField(default=0, verbose_name='\u6570\u636e\u5e93'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='type1',
            field=models.IntegerField(default=0, verbose_name='WEB\u670d\u52a1\u5668'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='type2',
            field=models.IntegerField(default=0, verbose_name='\u8ba1\u5212\u4efb\u52a1'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='type3',
            field=models.IntegerField(default=0, verbose_name='\u914d\u7f6e\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='type4',
            field=models.IntegerField(default=0, verbose_name='\u5176\u4ed6'),
        ),
    ]
