# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-23 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171024_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='readnum',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
    ]
