# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180105_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='note',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('0', '无'), ('1', '总监'), ('2', '经理'), ('3', '研发')], default='0', max_length=1),
        ),
    ]
