# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-08 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='echarts_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=10, verbose_name='\u63d0\u4ea4\u4eba')),
                ('web', models.CharField(max_length=10, verbose_name='Web\u7c7b\u578b')),
                ('db', models.CharField(max_length=10, verbose_name='DB\u7c7b\u578b')),
                ('crontab', models.CharField(max_length=10, verbose_name='crontab\u7c7b\u578b')),
                ('conf', models.CharField(max_length=10, verbose_name='conf\u7c7b\u578b')),
                ('other', models.CharField(max_length=10, verbose_name='other\u7c7b\u578b')),
                ('data_collection_time', models.IntegerField(verbose_name='\u6570\u636e\u6536\u96c6\u65f6\u95f4')),
            ],
        ),
    ]
