# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-08 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_echarts_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echarts_order',
            old_name='name_cn',
            new_name='uid',
        ),
    ]
