# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-08 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_auto_20180408_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echarts_order',
            name='data_collection_time',
            field=models.CharField(max_length=10, verbose_name='\u6570\u636e\u6536\u96c6\u65f6\u95f4'),
        ),
    ]
