# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-09 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180107_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='book',
            name='clicknum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='sellnum',
            field=models.IntegerField(default=0),
        ),
    ]
