# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180109_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fansnum',
            new_name='fans',
        ),
    ]
